import Arrow from './Arrow'

/**
 * Uses the provided markup as the image for the arrows.
 * The left one is expected, the others will be generated by rotation.
 **/
export default class ArrowMarkup extends Arrow {
  static check (options) {
    return Boolean(options.arrowMarkup)
  }

  create (instance) {
    this.setArrowMarkup(instance)
  }

  update (instance) {
    this.setArrowMarkup(instance)
  }

  setArrowMarkup (instance) {
    const arrowMarkup = this.options.arrowMarkup

    instance.directions.map(direction => {
      const arrow = instance.arrows[direction]

      arrow.innerHTML = arrowMarkup

      const markupNode = arrow.childNodes[0]

      this.setArrowRotation(markupNode, direction)
      this.setMarkupSize(markupNode)
      this.hideDefaultArrows(arrow)
    })

    this.setArrowPosition(instance)
  }

  setMarkupSize (markupNode) {
    const fadeWidth = this.options.fadeWidth

    markupNode.style.width = fadeWidth
    markupNode.style.height = fadeWidth
  }
}
